#app.static.version: "0"
app:
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
  #  errorCodeFiles:
  #    - errorCode.yml
  sessionPack:
    appName: rx
    version: 0.1
#  static.version: "1"
#  static:
#    version: "2"
