app:
  threadPool:
    initSize: 0
    keepAliveSeconds: 600
    queueCapacity: 0
    lowCpuWaterMark: 40
    highCpuWaterMark: 70
    resizeQuantity: 2
    scheduleInitSize: 1
  net:
    reactorThreadAmount: 0
    enableLog: false
    connectTimeoutMillis: 16000
    poolMaxSize: 0
    poolKeepAliveSeconds: 120
    userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 QBCore/4.0.1301.400 QQBrowser/9.0.2524.400 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2875.116 Safari/537.36 NetType/WIFI MicroMessenger/7.0.5 WindowsWechat
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
    - org.springframework.validation.BindingResult
    - org.rx.io.IOStream

tst:
  - name: a
    age: 1
  - name: b
    age: 2
