app:
  defaultBufferSize: 1024
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
  #  errorCodeFiles:
  #    - errorCode.yml
  sessionPack:
    appName: rx
    version: 0.1

  test.version: 1
  test:
    version: 2
app.test.version: 0
