app:
  bufferSize: 512
  netTimeoutMillis: 16000
  netMinPoolSize: 2
  netMaxPoolSize: 0
  cacheExpireMinutes: 4
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
  #  errorCodeFiles:
  #    - errorCode.yml

  test.version: 2
app.test.version: 1
