app:
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
  netProxy:
    compression: true
    listenBlock: false
#  errorCodeFiles:
#    - rxCode.yml
