app:
  bufferSize: 512
  socksTimeout: 20000
  jsonSkipTypes:
    - javax.servlet.ServletRequest
    - javax.servlet.ServletResponse
    - org.springframework.ui.Model
  #  errorCodeFiles:
  #    - errorCode.yml
  appId: rx

  test.version: 1
  test:
    version: 2
app.test.version: 0
