#app:
#  id: Rx
#  threadPool:
#    replicas: 4
#  net:
#    reactorThreadAmount: 2
#    connectTimeoutMillis: 40000
#  logTypeWhitelist:
#    - org.rx
#    - com.net
#  jsonSkipTypes:
#    - java.lang.String
