server.port: 80

spring.profiles.active: prd
spring.datasource.driverClassName: com.mysql.jdbc.Driver
mybatis.type-aliases-package: org.rx.fl.repository.model
mybatis.config-location: classpath:mybatis-config.xml
mybatis.mapper-locations: classpath:mybatis/*.xml

app.errorCodeFiles:
  - errorCode.yml
app.mybatis.mapperScan: org.rx.fl.repository
app.commandList: FindAdvCmd,RebindOrderCmd,UserDashboardCmd,BindPaymentCmd,WithdrawCmd,DailyCheckInCmd,QueryOrderCmd,FeedbackCmd,SubscribeCmd
app.sms.appId: 1400123840
app.sms.appKey: 0decfdc628b7d885a790524133f22339
app.sms.smsSign: 隽斋

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://r.x.org:3306/rx_rebate_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rx_rebate_dev_user
    password: e)ud(yB_g8uO
app:
  awtBot:
    logPath: /usr/awtBot
    delay: 10
  chrome:
    driver: /usr/chrome/chromedriver.exe
    dataPath: /usr/chrome/data
    downloadPath: /usr/chrome/download
    isBackground: false
    initSize: 0
  ie:
    driver: /usr/chrome/IEDriverServer.exe
    cookieUrl: http://x.%s/index.html?cookie=1  #需要配置hosts
    initSize: 0
  media:
    maxUserCount: 1000
    syncWeeklyOrderSeconds: 80
    syncMonthlyOrderSeconds: 28800
    commandTimeout: 30
    remoteMode: false
    remoteEndpoint: 127.0.0.1:80
    cacheSeconds: 180
    taobao:
      coreSize: 0
      keepLoginSeconds: 90
    jd:
      coreSize: 1
      keepLoginSeconds: 60
      loginPort: 8081
  repository.dbFile: /usr/lr.db

---

spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://r.x.org:3306/rx_rebate_prd?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rx_rebate_prd_user
    password: pL1ae4Q%L8TK$sD%
app:
  awtBot:
    logPath: C:\_rx\awtBot
    delay: 10
  chrome:
    driver: C:\_rx\chrome\chromedriver.exe
    dataPath: C:\_rx\chrome\data
    downloadPath: C:\_rx\chrome\download
    isBackground: false
    initSize: 3
  ie:
    driver: C:\_rx\chrome\IEDriverServer.exe
    cookieUrl: http://x.%s/index.html?cookie=1
    initSize: 1
  media:
    maxUserCount: 1000
    syncWeeklyOrderSeconds: 80
    syncMonthlyOrderSeconds: 28800
    commandTimeout: 60
    remoteMode: false
    remoteEndpoint: 127.0.0.1:80
    cacheSeconds: 180
    taobao:
      coreSize: 1
      keepLoginSeconds: 90
    jd:
      coreSize: 1
      keepLoginSeconds: 60
      loginPort: 8081
  repository.dbFile: /_rx/lr.db
