server.port: 8080

#spring.profiles.active: dev
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/rx_rebate?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username: root
spring.datasource.password: rx-root
mybatis.type-aliases-package: org.rx.fl.repository.model
mybatis.config-location: classpath:mybatis-config.xml
mybatis.mapper-locations: classpath:mybatis/*.xml

app:
  chrome:
    driver: D:\usr\chrome\chromedriver.exe
    dataPath: D:\usr\chrome\data
    downloadPath: D:\usr\chrome\download
    isBackground: false
    initSize: 0
  ie:
    driver: D:\usr\chrome\IEDriverServer.exe
    cookieUrl: http://x.%s:${server.port}/media/index.html?rx=1  #需要配置hosts
    initSize: 0
  media:
    coreSize: 0
    maxUserCount: 1000
    syncWeeklyOrderSeconds: 80
    syncMonthlyOrderSeconds: 28800
    commandTimeout: 60
    remoteMode: false
    remoteEndpoint: 127.0.0.1:8080
    cacheSeconds: 180
    tbKeepPeriod: 80
  errorCodeFiles:
  - errorCode.yml
  mybatis:
    mapperScan: org.rx.fl.repository
  repository:
    dbFile: /usr/local/_rx/db/rx.dat
  sms:
    appId: 1400123840
    appKey: 0decfdc628b7d885a790524133f22339
    smsSign: 隽斋
