server.port: 8080

spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/rx_rebate?useUnicode=true&characterEncoding=utf-8
spring.datasource.username: root
spring.datasource.password: rx-root
mybatis.type-aliases-package: org.rx.fl.repository.model
mybatis.config-location: classpath:mybatis-config.xml
mybatis.mapper-locations: classpath:mybatis/*.xml

app:
  mybatis:
    mapperScan: org.rx.fl.repository
  chrome:
    driver: D:\usr\chrome\chromedriver.exe
    logPath: D:\usr\chrome\logs
    dataPath: D:\usr\chrome\data
    downloadPath: D:\usr\chrome\download
    isBackground: false
    initSize: 2
  media:
    coreSize: 1
    remoteMode: false
    remoteEndpoint: 127.0.0.1:8080
  repository:
    dbFile: /usr/local/_rx/db/rx.dat
  sms:
    appId: 1400123840
    appKey: 0decfdc628b7d885a790524133f22339
    smsSign: 隽斋
