app:
  chrome:
    driver: D:\usr\chrome\chromedriver.exe
    dataPath: D:\usr\chrome\data
    downloadPath: D:\usr\chrome\download
    isBackground: false
    initSize: 0
  ie:
    driver: D:\usr\chrome\IEDriverServer.exe
    getCookieUrl: http://pubrx.alimama.com:8080/media/coupon.html?rx=1  #需要配置hosts
    initSize: 0
  media:
    coreSize: 0
    maxUserCount: 1000
    syncOrderPeriod: 70
    commandTimeout: 60
    remoteMode: false
    remoteEndpoint: 127.0.0.1:8080
    tbKeepPeriod: 80
    cacheSeconds: 180
