spring.datasource.url: jdbc:mysql://r.x.org:3306/rx_rebate_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username: rx_rebate_dev_user
spring.datasource.password: e)ud(yB_g8uO