server.port: 80

spring.profiles.active: prd
spring.datasource.driverClassName: com.mysql.jdbc.Driver
mybatis.type-aliases-package: org.rx.fl.repository.model
mybatis.config-location: classpath:mybatis-config.xml
mybatis.mapper-locations: classpath:mybatis/*.xml

app.errorCodeFiles:
  - errorCode.yml
app.mybatis.mapperScan: org.rx.fl.repository
app.commandList: CommissionCmd,FindAdvCmd,RebindOrderCmd,UserDashboardCmd,BindPaymentCmd,WithdrawCmd,DailyCheckInCmd,QueryOrderCmd,FeedbackCmd,AliPayCmd,SubscribeCmd
#app.bot.debugPath: /app_rebate/bot/
app.repository.dbFile: /app_rebate/lr.db
app.sms.appId: 1400123840
app.sms.appKey: 0decfdc628b7d885a790524133f22339
app.sms.smsSign: 隽斋

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:4306/rx_rebate_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rx_rebate_dev_user
    password: e)ud(yB_g8uO
app:
  bot:
    wx-mobile:
      capturePeriod: 500
      maxCheckMessageCount: 2
      maxCaptureMessageCount: 1
      maxScrollMessageCount: 1
      captureScrollSeconds: 10
      autoResetWindow: false
  media:
    enableMedias: Taobao,Jd
    syncWeeklyOrderSeconds: 80
    syncMonthlyOrderTime: "02:30:00"
    commandTimeout: 20
    goodsCacheMinutes: 600
    advCacheMinutes: 720
    protectAmount: 1
    remoteMode: false
    remoteEndpoint: 127.0.0.1:80
    taobao:
      coreSize: 0
      keepLoginSeconds: 90
      rootPercent: 95
      guideUrl: http://t.cn/EVYaBsn
      fzGuideUrl: http://t.cn/Efs0iCn
    jd:
      coreSize: 0
      keepLoginSeconds: 70
      loginPort: 8081
      rootPercent: 95
      guideUrl: http://t.cn/EcsaJnC
    pdd:
      coreSize: 0
      keepLoginSeconds: 60
  browser:
    windowRectangle: 0,0,1024,800
    errorCountToExchange: 4
    chrome:
      driver: /usr/chrome/chromedriver.exe
      dataPath: /usr/chrome/data
      downloadPath: /usr/chrome/download
      isBackground: false
      initSize: 0
    ie:
      driver: /usr/chrome/IEDriverServer.exe
      cookieUrl: http://x.%s/rx.html?cookie=1
      initSize: 0
  user:
    adminIds:
      - c7bc68c9-d6f0-da3b-e3a7-7db62fd0d567
    relations:
      - 1-1,90
      - 2-?,80
    heartbeatMinutes: 20
    dataFilePath: /usr/chrome
    intro: 小范省钱，京东、淘宝、天猫、飞猪和拼多多的商品以内部价拿优惠券购买，还能返现拿现金。返现提现当天到帐无手续费！将小范儿内部购微信名片推荐给好友，永久享受额外20%返现提成！
    aliPayCode: #打开支付宝首页搜“546289253”领红包，领到大红包的小伙伴赶紧使用哦！
    groupAliPay:
      - A小范省钱分享群
    groupAliPayTime:
      - "08:00:00"
      - "10:50:00"
      - "12:10:00"
      - "18:00:00"
    groupGoods:
      - A小范省钱分享群
    groupGoodsTime:
      - "08:00:00"
    groupGoodsName:
      - 垃圾袋
      - 洗衣液

---

spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rx_rebate_prd?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rx_rebate_prd_user
    password: pL1ae4Q%L8TK$sD%
app:
  bot:
    wx-mobile:
      capturePeriod: 700
      maxCheckMessageCount: 2
      maxCaptureMessageCount: 1
      maxScrollMessageCount: 1
      captureScrollSeconds: 24
      autoResetWindow: true
  media:
    enableMedias: Taobao,Jd
    syncWeeklyOrderSeconds: 90
    syncMonthlyOrderTime: "02:30:00"
    commandTimeout: 30
    goodsCacheMinutes: 600
    advCacheMinutes: 720
    protectAmount: 1
    remoteMode: false
    remoteEndpoint: 127.0.0.1:80
    taobao:
      coreSize: 1
      keepLoginSeconds: 90
      rootPercent: 98
      guideUrl: http://t.cn/EVYaBsn
      fzGuideUrl: http://t.cn/Efs0iCn
    jd:
      coreSize: 1
      keepLoginSeconds: 60
      loginPort: 8081
      rootPercent: 95
      guideUrl: http://t.cn/EItLAdX
    pdd:
      coreSize: 0
      keepLoginSeconds: 60
  browser:
    windowRectangle: 800,1000,800,600
    errorCountToExchange: 3
    chrome:
      driver: /app_rebate/chrome/chromedriver.exe
      dataPath: /app_rebate/chrome/data
      downloadPath: /app_rebate/chrome/download
      isBackground: false
      initSize: 3
    ie:
      driver: /app_rebate/chrome/IEDriverServer.exe
      cookieUrl: http://x.%s/rx.html?cookie=1
      initSize: 1
  user:
    adminIds:
      - 678196b6-fbf8-6fa4-bb76-3a0b34fe4746
    relations:
      - 1-1,100
      - 2-?,80
    heartbeatMinutes: 20
    dataFilePath: /app_rebate/data
    intro: 小范省钱，京东、淘宝、天猫、飞猪和拼多多的商品以内部价拿优惠券购买，还能返现拿现金。返现提现当天到帐无手续费！将小范儿内部购微信名片推荐给好友，永久享受额外20%返现提成！
    aliPayCode: 打开支付宝首页搜“546289253”领红包，领到大红包的小伙伴赶紧使用哦！
    groupAliPay:
      - A小范省钱分享群
      - 红包官方分享群
    #      - 苏州美家
    groupAliPayTime:
      - "08:00:00"
      - "10:50:00"
      - "12:10:00"
      - "18:00:00"
    groupGoods:
      - A小范省钱分享群
    groupGoodsTime:
      - "08:00:00"
      - "12:00:00"
      - "18:00:00"
    groupGoodsName:
      - 垃圾袋
      - 洗衣液
      - 牛奶
      - 猫爪杯
